"""
AI Text Generation Detector Agent
Analyzes text content for signs of AI generation (ChatGPT, Claude, etc.).
Uses NVIDIA NIM for intelligent stylometric analysis.
"""

import json
from typing import Dict, Any
from loguru import logger


class TextGenDetectorAgent:
    """Detects AI-generated text in documents and content."""

    def __init__(self):
        from core.nim_client import get_nim_client
        self.nim = get_nim_client()

    async def analyze(self, text: str, context: str = "") -> Dict[str, Any]:
        """Analyze text for AI generation indicators.

        Args:
            text: Text content to analyze.
            context: Optional context about expected content.

        Returns:
            Dict with AI text detection results.
        """
        logger.info(f"Text Gen Detector: analyzing {len(text)} chars")

        # Split text into paragraphs for per-paragraph analysis
        paragraphs = [p.strip() for p in text.split('\n\n') if p.strip() and len(p.strip()) > 30]
        para_list = "\n---\n".join(f"[Paragraph {i+1}]: {p[:500]}" for i, p in enumerate(paragraphs[:15]))

        prompt = f"""You are an expert AI text detection analyst. Your job is to determine whether text was written by a human or generated by AI (ChatGPT, Claude, Gemini, etc.).

Analyze the following text for AI generation indicators.

TEXT TO ANALYZE:
{text[:5000]}

PARAGRAPHS:
{para_list}

{f"CONTEXT: {context[:500]}" if context else ""}

Check for these AI text indicators:
1. **Perplexity**: Unusually consistent, predictable word choices (AI tends to be more uniform)
2. **Burstiness**: Lack of variation in sentence length and complexity (humans vary more)
3. **Repetitive patterns**: Repeated phrases, structures, or transitional patterns
4. **Vocabulary distribution**: Unusually broad or narrow vocabulary for the context
5. **Hedging language**: Excessive qualifiers ("It's important to note...", "It should be mentioned...")
6. **List patterns**: Over-reliance on structured lists and bullet points
7. **Emotional flatness**: Lack of genuine personal voice or emotional variation
8. **Perfect grammar**: Suspiciously error-free writing with no typos or informal language

Return a JSON object:
{{
    "ai_probability": 0.0-1.0,
    "risk_score": 0-100,
    "classification": "likely_ai|possibly_ai|uncertain|likely_human",
    "indicators": [
        {{
            "type": "perplexity|burstiness|repetition|vocabulary|hedging|list_pattern|emotional|grammar",
            "severity": "critical|high|medium|low",
            "description": "detailed explanation",
            "confidence": 0.0-1.0
        }}
    ],
    "paragraph_analysis": [
        {{
            "paragraph_num": 1,
            "ai_probability": 0.0-1.0,
            "classification": "likely_ai|possibly_ai|uncertain|likely_human",
            "notes": "brief analysis"
        }}
    ],
    "stylometric_features": {{
        "avg_sentence_length": 0,
        "vocabulary_richness": "low|medium|high",
        "formality_level": "low|medium|high",
        "hedging_frequency": "low|medium|high"
    }},
    "summary": "brief narrative of findings"
}}"""

        try:
            response = await self.nim.chat(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=2000,
            )

            try:
                text_resp = response.strip()
                if "```json" in text_resp:
                    text_resp = text_resp.split("```json")[1].split("```")[0]
                elif "```" in text_resp:
                    text_resp = text_resp.split("```")[1].split("```")[0]
                result = json.loads(text_resp)
            except (json.JSONDecodeError, IndexError):
                result = {
                    "ai_probability": 0.5,
                    "risk_score": 50,
                    "classification": "uncertain",
                    "indicators": [],
                    "summary": response[:500],
                    "_raw_response": True,
                }

            logger.info(f"Text Gen Detection complete. AI probability: {result.get('ai_probability', 0)}")
            return result

        except Exception as e:
            logger.error(f"Text Gen Detector error: {e}")
            return {
                "ai_probability": 0.0,
                "risk_score": 0,
                "classification": "uncertain",
                "indicators": [],
                "summary": f"Analysis error: {str(e)}",
                "error": str(e),
            }
